// app/layout.tsx

import './globals.css';
import ReduxProvider from '../src/components/reduxProvider'; // Import your client-side Redux provider
import ClientLayout from './clientLayout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ClientLayout>{children}</ClientLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
